//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interseguro.CWRV.Presentacion.ASPNET.RentaPrivadaPlus {
    
    
    public partial class GrupoFamiliarAfiliado {
        
        /// <summary>
        /// Grupo_Familiar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel Grupo_Familiar;
        
        /// <summary>
        /// HCUSPP_RP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField HCUSPP_RP;
        
        /// <summary>
        /// ModGruFamModo_RP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField ModGruFamModo_RP;
        
        /// <summary>
        /// ModIdGrupoFamiliar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField ModIdGrupoFamiliar;
        
        /// <summary>
        /// ModPaginaLlamada control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField ModPaginaLlamada;
        
        /// <summary>
        /// ModGruFamLineaApellidos_RP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel ModGruFamLineaApellidos_RP;
        
        /// <summary>
        /// ModGruFamApellidoPaterno_RP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ModGruFamApellidoPaterno_RP;
        
        /// <summary>
        /// ModGruFamApellidoMaterno_RP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ModGruFamApellidoMaterno_RP;
        
        /// <summary>
        /// ModGruFamLineaNombres_RP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel ModGruFamLineaNombres_RP;
        
        /// <summary>
        /// ModGruFamNombres_RP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ModGruFamNombres_RP;
        
        /// <summary>
        /// ModGruFamLineaIdentificacion_RP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel ModGruFamLineaIdentificacion_RP;
        
        /// <summary>
        /// ModGruFamTipoIdentificacion_RP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ModGruFamTipoIdentificacion_RP;
        
        /// <summary>
        /// ModGruFamNumeroIdentificacion_RP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ModGruFamNumeroIdentificacion_RP;
        
        /// <summary>
        /// ModGruFamLineaParentesco_RP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel ModGruFamLineaParentesco_RP;
        
        /// <summary>
        /// ModGruFamParentesco_RP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ModGruFamParentesco_RP;
        
        /// <summary>
        /// ModGruFamLineaSexoNacimiento_RP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel ModGruFamLineaSexoNacimiento_RP;
        
        /// <summary>
        /// ModGruFamSexo_RP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ModGruFamSexo_RP;
        
        /// <summary>
        /// ModGruFamFechaNacimiento_RP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ModGruFamFechaNacimiento_RP;
        
        /// <summary>
        /// ModGruFamLineaInvalidez_RP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel ModGruFamLineaInvalidez_RP;
        
        /// <summary>
        /// ModGruFamIndInvalidez_RP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ModGruFamIndInvalidez_RP;
        
        /// <summary>
        /// ModGruFamTipoInvalidez_RP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ModGruFamTipoInvalidez_RP;
        
        /// <summary>
        /// ModGruFamLineaFechaInvalidez_RP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel ModGruFamLineaFechaInvalidez_RP;
        
        /// <summary>
        /// ModGruFamFechaInvalidez_RP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ModGruFamFechaInvalidez_RP;
        
        /// <summary>
        /// ModGruFamLineaNacionalProfesion_RP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel ModGruFamLineaNacionalProfesion_RP;
        
        /// <summary>
        /// ModGruFamNacional_RP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ModGruFamNacional_RP;
        
        /// <summary>
        /// ModGruFamProfesion_RP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ModGruFamProfesion_RP;
        
        /// <summary>
        /// ModGruFamLineaResidencia_RP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel ModGruFamLineaResidencia_RP;
        
        /// <summary>
        /// ModGruFamResidencia_RP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ModGruFamResidencia_RP;
        
        /// <summary>
        /// ModGruFamLineaPEP_RP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel ModGruFamLineaPEP_RP;
        
        /// <summary>
        /// ModGruFamPEP_RP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ModGruFamPEP_RP;
        
        /// <summary>
        /// ModGruFamSO_RP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ModGruFamSO_RP;
        
        /// <summary>
        /// ModGruFamLineaBanco_RP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel ModGruFamLineaBanco_RP;
        
        /// <summary>
        /// ModGruFamBanco_RP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ModGruFamBanco_RP;
        
        /// <summary>
        /// ModGruFamTipoCtaBanco_RP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ModGruFamTipoCtaBanco_RP;
        
        /// <summary>
        /// ModGruFamLineaNroBanco_RP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel ModGruFamLineaNroBanco_RP;
        
        /// <summary>
        /// ModGruFamNumeroBanco_RP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ModGruFamNumeroBanco_RP;
        
        /// <summary>
        /// ModGruFamLineaComunicacion_RP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel ModGruFamLineaComunicacion_RP;
        
        /// <summary>
        /// ModGruFamComunicacion_RP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ModGruFamComunicacion_RP;
        
        /// <summary>
        /// ModGruFamConfidencialidadDatos_RP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ModGruFamConfidencialidadDatos_RP;
        
        /// <summary>
        /// MCMContenedor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel MCMContenedor;
        
        /// <summary>
        /// MCMEstado control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField MCMEstado;
        
        /// <summary>
        /// MCMEstadoIcono control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField MCMEstadoIcono;
        
        /// <summary>
        /// MCMEstadoTitulo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField MCMEstadoTitulo;
        
        /// <summary>
        /// MCMMensaje control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal MCMMensaje;
        
        /// <summary>
        /// MCAContenedor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel MCAContenedor;
        
        /// <summary>
        /// MCAEstado control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField MCAEstado;
        
        /// <summary>
        /// MCAEstadoIcono control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField MCAEstadoIcono;
        
        /// <summary>
        /// MCAEstadoTitulo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField MCAEstadoTitulo;
        
        /// <summary>
        /// MCAMensaje control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal MCAMensaje;
        
        /// <summary>
        /// MCATablaEliminar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField MCATablaEliminar;
    }
}
