//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BEOpcionMenu", Namespace="http://schemas.datacontract.org/2004/07/Interseguro.Azman.Entidades")]
    [System.SerializableAttribute()]
    public partial class BEOpcionMenu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoOpcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CodigoOpcionPadreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionOperacionAzmanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreOperacionzmanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NroOperacionAzmanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrdenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutaIconoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoOpcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToolTipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool VisibleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoOpcion {
            get {
                return this.CodigoOpcionField;
            }
            set {
                if ((this.CodigoOpcionField.Equals(value) != true)) {
                    this.CodigoOpcionField = value;
                    this.RaisePropertyChanged("CodigoOpcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodigoOpcionPadre {
            get {
                return this.CodigoOpcionPadreField;
            }
            set {
                if ((this.CodigoOpcionPadreField.Equals(value) != true)) {
                    this.CodigoOpcionPadreField = value;
                    this.RaisePropertyChanged("CodigoOpcionPadre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionOperacionAzman {
            get {
                return this.DescripcionOperacionAzmanField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionOperacionAzmanField, value) != true)) {
                    this.DescripcionOperacionAzmanField = value;
                    this.RaisePropertyChanged("DescripcionOperacionAzman");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreOperacionzman {
            get {
                return this.NombreOperacionzmanField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreOperacionzmanField, value) != true)) {
                    this.NombreOperacionzmanField = value;
                    this.RaisePropertyChanged("NombreOperacionzman");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NroOperacionAzman {
            get {
                return this.NroOperacionAzmanField;
            }
            set {
                if ((this.NroOperacionAzmanField.Equals(value) != true)) {
                    this.NroOperacionAzmanField = value;
                    this.RaisePropertyChanged("NroOperacionAzman");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Orden {
            get {
                return this.OrdenField;
            }
            set {
                if ((this.OrdenField.Equals(value) != true)) {
                    this.OrdenField = value;
                    this.RaisePropertyChanged("Orden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RutaIcono {
            get {
                return this.RutaIconoField;
            }
            set {
                if ((object.ReferenceEquals(this.RutaIconoField, value) != true)) {
                    this.RutaIconoField = value;
                    this.RaisePropertyChanged("RutaIcono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoOpcion {
            get {
                return this.TipoOpcionField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoOpcionField, value) != true)) {
                    this.TipoOpcionField = value;
                    this.RaisePropertyChanged("TipoOpcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToolTip {
            get {
                return this.ToolTipField;
            }
            set {
                if ((object.ReferenceEquals(this.ToolTipField, value) != true)) {
                    this.ToolTipField = value;
                    this.RaisePropertyChanged("ToolTip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Visible {
            get {
                return this.VisibleField;
            }
            set {
                if ((this.VisibleField.Equals(value) != true)) {
                    this.VisibleField = value;
                    this.RaisePropertyChanged("Visible");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServicioError", Namespace="http://schemas.datacontract.org/2004/07/Interseguro.Azman.Servicios")]
    [System.SerializableAttribute()]
    public partial class ServicioError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContenidoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contenido {
            get {
                return this.ContenidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContenidoField, value) != true)) {
                    this.ContenidoField = value;
                    this.RaisePropertyChanged("Contenido");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BEUsuario", Namespace="http://schemas.datacontract.org/2004/07/Interseguro.Azman.Entidades")]
    [System.SerializableAttribute()]
    public partial class BEUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DominioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatriculaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCompletoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RolAzmanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idAplicacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idRolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int indVigenciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoEmpleado {
            get {
                return this.CodigoEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoEmpleadoField, value) != true)) {
                    this.CodigoEmpleadoField = value;
                    this.RaisePropertyChanged("CodigoEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dominio {
            get {
                return this.DominioField;
            }
            set {
                if ((object.ReferenceEquals(this.DominioField, value) != true)) {
                    this.DominioField = value;
                    this.RaisePropertyChanged("Dominio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Matricula {
            get {
                return this.MatriculaField;
            }
            set {
                if ((object.ReferenceEquals(this.MatriculaField, value) != true)) {
                    this.MatriculaField = value;
                    this.RaisePropertyChanged("Matricula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCompleto {
            get {
                return this.NombreCompletoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCompletoField, value) != true)) {
                    this.NombreCompletoField = value;
                    this.RaisePropertyChanged("NombreCompleto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rol {
            get {
                return this.RolField;
            }
            set {
                if ((object.ReferenceEquals(this.RolField, value) != true)) {
                    this.RolField = value;
                    this.RaisePropertyChanged("Rol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RolAzman {
            get {
                return this.RolAzmanField;
            }
            set {
                if ((object.ReferenceEquals(this.RolAzmanField, value) != true)) {
                    this.RolAzmanField = value;
                    this.RaisePropertyChanged("RolAzman");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idAplicacion {
            get {
                return this.idAplicacionField;
            }
            set {
                if ((this.idAplicacionField.Equals(value) != true)) {
                    this.idAplicacionField = value;
                    this.RaisePropertyChanged("idAplicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idRol {
            get {
                return this.idRolField;
            }
            set {
                if ((object.ReferenceEquals(this.idRolField, value) != true)) {
                    this.idRolField = value;
                    this.RaisePropertyChanged("idRol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                if ((this.idUsuarioField.Equals(value) != true)) {
                    this.idUsuarioField = value;
                    this.RaisePropertyChanged("idUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int indVigencia {
            get {
                return this.indVigenciaField;
            }
            set {
                if ((this.indVigenciaField.Equals(value) != true)) {
                    this.indVigenciaField = value;
                    this.RaisePropertyChanged("indVigencia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Proxies.ModuloSeguridad.IServicioAzman")]
    public interface IServicioAzman {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAzman/ObtenerListaPermisos", ReplyAction="http://tempuri.org/IServicioAzman/ObtenerListaPermisosResponse")]
        Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.BEOpcionMenu[] ObtenerListaPermisos(string aplicacion, string dominio, string usuario, int idAplicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAzman/ObtenerListaPermisosConCredenciales", ReplyAction="http://tempuri.org/IServicioAzman/ObtenerListaPermisosConCredencialesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ServicioError), Action="http://tempuri.org/IServicioAzman/ObtenerListaPermisosConCredencialesServicioErro" +
            "rFault", Name="ServicioError", Namespace="http://schemas.datacontract.org/2004/07/Interseguro.Azman.Servicios")]
        Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.BEOpcionMenu[] ObtenerListaPermisosConCredenciales(string aplicacion, string dominio, string usuario, string contrasena, int idAplicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAzman/ObtenerDatosUsuario", ReplyAction="http://tempuri.org/IServicioAzman/ObtenerDatosUsuarioResponse")]
        Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.BEUsuario ObtenerDatosUsuario(string aplicacion, string dominio, string usuario, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAzman/ObtenerDatosUsuarioSinClave", ReplyAction="http://tempuri.org/IServicioAzman/ObtenerDatosUsuarioSinClaveResponse")]
        Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.BEUsuario ObtenerDatosUsuarioSinClave(string aplicacion, string dominio, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAzman/InsertarLog", ReplyAction="http://tempuri.org/IServicioAzman/InsertarLogResponse")]
        void InsertarLog(string codAplicacion, string nombreTerminal, string direccionIP, string usuario, System.DateTime fechaEvento, int codTipoEvento, string detalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAzman/InsertarLogSgi", ReplyAction="http://tempuri.org/IServicioAzman/InsertarLogSgiResponse")]
        int InsertarLogSgi(string codAplicacion, string nombreTerminal, string direccionIP, string usuario, System.DateTime fechaEvento, int codTipoEvento, string detalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAzman/ObtenerTablaRoles", ReplyAction="http://tempuri.org/IServicioAzman/ObtenerTablaRolesResponse")]
        System.Data.DataTable ObtenerTablaRoles(string aplicacion);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento aplicacion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAzman/ObtenerXMLRoles", ReplyAction="http://tempuri.org/IServicioAzman/ObtenerXMLRolesResponse")]
        Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLRolesResponse ObtenerXMLRoles(Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLRolesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento aplicacion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAzman/ObtenerXMLOperaciones", ReplyAction="http://tempuri.org/IServicioAzman/ObtenerXMLOperacionesResponse")]
        Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLOperacionesResponse ObtenerXMLOperaciones(Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLOperacionesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento aplicacion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAzman/ObtenerXMLUsuarios_Operaciones", ReplyAction="http://tempuri.org/IServicioAzman/ObtenerXMLUsuarios_OperacionesResponse")]
        Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLUsuarios_OperacionesResponse ObtenerXMLUsuarios_Operaciones(Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLUsuarios_OperacionesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento tipo del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAzman/ObtenerXMLLog", ReplyAction="http://tempuri.org/IServicioAzman/ObtenerXMLLogResponse")]
        Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLLogResponse ObtenerXMLLog(Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLLogRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerXMLRolesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerXMLRoles", Namespace="http://tempuri.org/", Order=0)]
        public Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLRolesRequestBody Body;
        
        public ObtenerXMLRolesRequest() {
        }
        
        public ObtenerXMLRolesRequest(Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLRolesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerXMLRolesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string aplicacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombreRol;
        
        public ObtenerXMLRolesRequestBody() {
        }
        
        public ObtenerXMLRolesRequestBody(string aplicacion, string nombreRol) {
            this.aplicacion = aplicacion;
            this.nombreRol = nombreRol;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerXMLRolesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerXMLRolesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLRolesResponseBody Body;
        
        public ObtenerXMLRolesResponse() {
        }
        
        public ObtenerXMLRolesResponse(Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLRolesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerXMLRolesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement ObtenerXMLRolesResult;
        
        public ObtenerXMLRolesResponseBody() {
        }
        
        public ObtenerXMLRolesResponseBody(System.Xml.Linq.XElement ObtenerXMLRolesResult) {
            this.ObtenerXMLRolesResult = ObtenerXMLRolesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerXMLOperacionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerXMLOperaciones", Namespace="http://tempuri.org/", Order=0)]
        public Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLOperacionesRequestBody Body;
        
        public ObtenerXMLOperacionesRequest() {
        }
        
        public ObtenerXMLOperacionesRequest(Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLOperacionesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerXMLOperacionesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string aplicacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombreRol;
        
        public ObtenerXMLOperacionesRequestBody() {
        }
        
        public ObtenerXMLOperacionesRequestBody(string aplicacion, string nombreRol) {
            this.aplicacion = aplicacion;
            this.nombreRol = nombreRol;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerXMLOperacionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerXMLOperacionesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLOperacionesResponseBody Body;
        
        public ObtenerXMLOperacionesResponse() {
        }
        
        public ObtenerXMLOperacionesResponse(Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLOperacionesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerXMLOperacionesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement ObtenerXMLOperacionesResult;
        
        public ObtenerXMLOperacionesResponseBody() {
        }
        
        public ObtenerXMLOperacionesResponseBody(System.Xml.Linq.XElement ObtenerXMLOperacionesResult) {
            this.ObtenerXMLOperacionesResult = ObtenerXMLOperacionesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerXMLUsuarios_OperacionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerXMLUsuarios_Operaciones", Namespace="http://tempuri.org/", Order=0)]
        public Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLUsuarios_OperacionesRequestBody Body;
        
        public ObtenerXMLUsuarios_OperacionesRequest() {
        }
        
        public ObtenerXMLUsuarios_OperacionesRequest(Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLUsuarios_OperacionesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerXMLUsuarios_OperacionesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string aplicacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombreRol;
        
        public ObtenerXMLUsuarios_OperacionesRequestBody() {
        }
        
        public ObtenerXMLUsuarios_OperacionesRequestBody(string aplicacion, string nombreRol) {
            this.aplicacion = aplicacion;
            this.nombreRol = nombreRol;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerXMLUsuarios_OperacionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerXMLUsuarios_OperacionesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLUsuarios_OperacionesResponseBody Body;
        
        public ObtenerXMLUsuarios_OperacionesResponse() {
        }
        
        public ObtenerXMLUsuarios_OperacionesResponse(Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLUsuarios_OperacionesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerXMLUsuarios_OperacionesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement ObtenerXMLUsuarios_OperacionesResult;
        
        public ObtenerXMLUsuarios_OperacionesResponseBody() {
        }
        
        public ObtenerXMLUsuarios_OperacionesResponseBody(System.Xml.Linq.XElement ObtenerXMLUsuarios_OperacionesResult) {
            this.ObtenerXMLUsuarios_OperacionesResult = ObtenerXMLUsuarios_OperacionesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerXMLLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerXMLLog", Namespace="http://tempuri.org/", Order=0)]
        public Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLLogRequestBody Body;
        
        public ObtenerXMLLogRequest() {
        }
        
        public ObtenerXMLLogRequest(Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerXMLLogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idAplicacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tipo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cadenaConexion;
        
        public ObtenerXMLLogRequestBody() {
        }
        
        public ObtenerXMLLogRequestBody(int idAplicacion, string tipo, string cadenaConexion) {
            this.idAplicacion = idAplicacion;
            this.tipo = tipo;
            this.cadenaConexion = cadenaConexion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerXMLLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerXMLLogResponse", Namespace="http://tempuri.org/", Order=0)]
        public Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLLogResponseBody Body;
        
        public ObtenerXMLLogResponse() {
        }
        
        public ObtenerXMLLogResponse(Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerXMLLogResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement ObtenerXMLLogResult;
        
        public ObtenerXMLLogResponseBody() {
        }
        
        public ObtenerXMLLogResponseBody(System.Xml.Linq.XElement ObtenerXMLLogResult) {
            this.ObtenerXMLLogResult = ObtenerXMLLogResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioAzmanChannel : Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.IServicioAzman, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioAzmanClient : System.ServiceModel.ClientBase<Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.IServicioAzman>, Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.IServicioAzman {
        
        public ServicioAzmanClient() {
        }
        
        public ServicioAzmanClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioAzmanClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioAzmanClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioAzmanClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.BEOpcionMenu[] ObtenerListaPermisos(string aplicacion, string dominio, string usuario, int idAplicacion) {
            return base.Channel.ObtenerListaPermisos(aplicacion, dominio, usuario, idAplicacion);
        }
        
        public Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.BEOpcionMenu[] ObtenerListaPermisosConCredenciales(string aplicacion, string dominio, string usuario, string contrasena, int idAplicacion) {
            return base.Channel.ObtenerListaPermisosConCredenciales(aplicacion, dominio, usuario, contrasena, idAplicacion);
        }
        
        public Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.BEUsuario ObtenerDatosUsuario(string aplicacion, string dominio, string usuario, string contrasena) {
            return base.Channel.ObtenerDatosUsuario(aplicacion, dominio, usuario, contrasena);
        }
        
        public Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.BEUsuario ObtenerDatosUsuarioSinClave(string aplicacion, string dominio, string usuario) {
            return base.Channel.ObtenerDatosUsuarioSinClave(aplicacion, dominio, usuario);
        }
        
        public void InsertarLog(string codAplicacion, string nombreTerminal, string direccionIP, string usuario, System.DateTime fechaEvento, int codTipoEvento, string detalle) {
            base.Channel.InsertarLog(codAplicacion, nombreTerminal, direccionIP, usuario, fechaEvento, codTipoEvento, detalle);
        }
        
        public int InsertarLogSgi(string codAplicacion, string nombreTerminal, string direccionIP, string usuario, System.DateTime fechaEvento, int codTipoEvento, string detalle) {
            return base.Channel.InsertarLogSgi(codAplicacion, nombreTerminal, direccionIP, usuario, fechaEvento, codTipoEvento, detalle);
        }
        
        public System.Data.DataTable ObtenerTablaRoles(string aplicacion) {
            return base.Channel.ObtenerTablaRoles(aplicacion);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLRolesResponse Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.IServicioAzman.ObtenerXMLRoles(Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLRolesRequest request) {
            return base.Channel.ObtenerXMLRoles(request);
        }
        
        public System.Xml.Linq.XElement ObtenerXMLRoles(string aplicacion, string nombreRol) {
            Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLRolesRequest inValue = new Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLRolesRequest();
            inValue.Body = new Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLRolesRequestBody();
            inValue.Body.aplicacion = aplicacion;
            inValue.Body.nombreRol = nombreRol;
            Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLRolesResponse retVal = ((Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.IServicioAzman)(this)).ObtenerXMLRoles(inValue);
            return retVal.Body.ObtenerXMLRolesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLOperacionesResponse Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.IServicioAzman.ObtenerXMLOperaciones(Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLOperacionesRequest request) {
            return base.Channel.ObtenerXMLOperaciones(request);
        }
        
        public System.Xml.Linq.XElement ObtenerXMLOperaciones(string aplicacion, string nombreRol) {
            Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLOperacionesRequest inValue = new Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLOperacionesRequest();
            inValue.Body = new Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLOperacionesRequestBody();
            inValue.Body.aplicacion = aplicacion;
            inValue.Body.nombreRol = nombreRol;
            Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLOperacionesResponse retVal = ((Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.IServicioAzman)(this)).ObtenerXMLOperaciones(inValue);
            return retVal.Body.ObtenerXMLOperacionesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLUsuarios_OperacionesResponse Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.IServicioAzman.ObtenerXMLUsuarios_Operaciones(Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLUsuarios_OperacionesRequest request) {
            return base.Channel.ObtenerXMLUsuarios_Operaciones(request);
        }
        
        public System.Xml.Linq.XElement ObtenerXMLUsuarios_Operaciones(string aplicacion, string nombreRol) {
            Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLUsuarios_OperacionesRequest inValue = new Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLUsuarios_OperacionesRequest();
            inValue.Body = new Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLUsuarios_OperacionesRequestBody();
            inValue.Body.aplicacion = aplicacion;
            inValue.Body.nombreRol = nombreRol;
            Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLUsuarios_OperacionesResponse retVal = ((Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.IServicioAzman)(this)).ObtenerXMLUsuarios_Operaciones(inValue);
            return retVal.Body.ObtenerXMLUsuarios_OperacionesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLLogResponse Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.IServicioAzman.ObtenerXMLLog(Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLLogRequest request) {
            return base.Channel.ObtenerXMLLog(request);
        }
        
        public System.Xml.Linq.XElement ObtenerXMLLog(int idAplicacion, string tipo, string cadenaConexion) {
            Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLLogRequest inValue = new Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLLogRequest();
            inValue.Body = new Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLLogRequestBody();
            inValue.Body.idAplicacion = idAplicacion;
            inValue.Body.tipo = tipo;
            inValue.Body.cadenaConexion = cadenaConexion;
            Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.ObtenerXMLLogResponse retVal = ((Interseguro.CWRV.Presentacion.AgenteServicios.Proxies.ModuloSeguridad.IServicioAzman)(this)).ObtenerXMLLog(inValue);
            return retVal.Body.ObtenerXMLLogResult;
        }
    }
}
